Repository cloudera/hue, pull requests merged in 2020-10, with the labels that each got.

#1327 [frontend] Fix issue where Jest can only resolve relative module imports
  jest.config.js
Labels: improvement

#1334 HUE-9509 [ui] Create AlertBox component
  desktop/core/src/desktop/js/components/InlineAlert.test.ts
  desktop/core/src/desktop/js/components/InlineAlert.vue
  desktop/core/src/desktop/js/components/__snapshots__/InlineAlert.test.ts.snap
Labels: feature, ui

#1333 [notebook] The default list of interpreter is not cached properly
  desktop/libs/notebook/src/notebook/api_tests.py
  desktop/libs/notebook/src/notebook/conf.py
Labels: bug, improvement
