Repository cloudera/hue, pull requests merged in 2021-11, with the labels that each got.

#2638 [editor] Update has_result_set from check_status response for public API
  desktop/libs/notebook/src/notebook/api.py
Labels: improvement, editor, api, python

#2555 CircleCI: Extract build jobs config to be reusable
  .circleci/config.yml
Labels: tools

#2642 Blog xlsx direct importer
  docs/gethue/content/en/posts/2021-11-15-create-sql-tables-from-excel-files.md
Labels: blog
