Repository cloudera/hue, pull requests merged in 2021-02, with the labels that each got.

#1737 [ui] Feedback on login when pressing <enter>
  desktop/core/src/desktop/templates/login.mako
Labels: ui

#1749 [libs] Upgrade pytz==2021.1
  desktop/conf.dist/hue.ini
  desktop/conf/pseudo-distributed.ini.tmpl
  desktop/core/requirements.txt
  docs/docs-site/content/administrator/configuration/connectors/_index.md
Labels: connector

#1805 [frontend] Tab selection not working after Vue3 migration, fixed it
  desktop/core/src/desktop/js/components/Tab.test.ts
  desktop/core/src/desktop/js/components/Tab.vue
  desktop/core/src/desktop/js/components/Tabs.vue
  desktop/core/src/desktop/js/components/__snapshots__/Tabs.test.ts.snap
Labels: ui

#1826 [frontend] hue-spinner was getting hidden behind other elements
  desktop/core/src/desktop/js/components/Spinner.vue
Labels: frontend

#1828 [frontend] UI components not working as expected
  desktop/core/src/desktop/js/components/DateRangePicker.vue
  desktop/core/src/desktop/js/components/FacetSelector.vue
  desktop/core/src/desktop/js/components/SearchInput.vue
  desktop/core/src/desktop/js/components/dropdown/DropdownDrawer.vue
  desktop/core/src/desktop/js/components/dropdown/DropdownPanel.vue
Labels: frontend

#1827 [frontend] Queries doesn't get refreshed
  apps/jobbrowser/src/jobbrowser/templates/job_browser.mako
Labels: frontend

#1830 [frontend] Types change for moment & file-saver
  desktop/core/src/desktop/js/types/types.ts
  package-lock.json
  package.json
Labels: frontend
