Repository cloudera/hue, pull requests merged in 2021-03, with the labels that each got.

#1847 [docs] Slight README simplification
  README.md
Labels: autosquash

#1846 [docs] Use SparkSql as dialect instead of sql
  desktop/conf.dist/hue.ini
  desktop/conf/pseudo-distributed.ini.tmpl
  docs/docs-site/content/administrator/configuration/connectors/_index.md
  tools/docker/hue/conf/z-hue-overrides.ini
  tools/docker/hue/conf3/z-hue-overrides.ini
Labels: autosquash

#1850 [frontend] Publishing web component wrapper as an NPM package
  desktop/core/src/desktop/js/vue/webComponentWrap.ts
  desktop/core/src/desktop/js/vue/wrapper/index.ts
  desktop/core/src/desktop/js/vue/wrapper/utils.ts
  tools/vue3-webcomponent-wrapper/.gitignore
  tools/vue3-webcomponent-wrapper/README.md
  tools/vue3-webcomponent-wrapper/package.json
  webpack.config.npm.js
Labels: frontend

#1854 [blog] Introducing Vue 3 & Web Components in Hue Query Editor
  docs/gethue/content/en/posts/2021-03-04-vue3-build-cli-options-composition-api-template-web-components-hue.md
Labels: blog

#1857 [docs] More help on blog post writing
  docs/docs-site/content/developer/development/_index.md
Labels: autosquash

#1855 [frontend] Improved vue3-webcomponent-wrapper README
  tools/vue3-webcomponent-wrapper/README.md
  tools/vue3-webcomponent-wrapper/package.json
Labels: frontend

#1866 [ci] More explicit message on how to keep issues not staled
  .github/workflows/autoclose-stale.yml
Labels: autosquash

#1867 [blog] Adding kubernetes rollout post
  docs/gethue/content/en/posts/2021-03-06-web-api-service-upgrade-no-downtime-kubernetes-rollout.md
Labels: autosquash

#1869 [ci] Bump number of items of staleness checker to catch-up
  .github/workflows/autoclose-stale.yml
Labels: autosquash

#1882 [blog] Fix Django upgrade post page name to properly load
  docs/gethue/content/en/posts/2021-03-09-process-and-learnings-when-upgrading-the-webserver-stack-django-upgrade-1.11-to-3.1.md
Labels: autosquash

#1871 [ci] Properly reset home to checked out repo for doc linting
  .github/workflows/commitflow.yml
Labels: autosquash

#1893 [connector] Do not enable Dashboard if main flag if off
  desktop/core/src/desktop/models.py
Labels: autosquash

#1896 support clone django babel through http proxy
  desktop/core/requirements.txt
Labels: autosquash

#1881 [npm] Adding a watched dev version of webpack-npm
  package.json
Labels: npm

#1904 [ci] Run autosquash only on the Hue repo branches
  .github/workflows/autosquash.yml
Labels: autosquash

#1910 [editor] Don't error on missing status for query history
  desktop/libs/notebook/src/notebook/api.py
Labels: autosquash

#1903 Table creation in Hive or Impala fails with UnicodeDecodeError: 'asci…
  apps/beeswax/gen-py/TCLIService/ttypes.py
  tools/ci/check_for_python_lint.sh
Labels: autosquash

#1909 [editor] Handle query history additions in the Query Table instead of in the snippet
  desktop/core/src/desktop/js/apps/editor/components/ExecutableProgressBar.test.ts
  desktop/core/src/desktop/js/apps/editor/components/ExecutableProgressBar.vue
  desktop/core/src/desktop/js/apps/editor/components/ExecuteButton.test.ts
  desktop/core/src/desktop/js/apps/editor/components/ExecuteButton.vue
  desktop/core/src/desktop/js/apps/editor/components/ExecuteLimitInput.vue
  desktop/core/src/desktop/js/apps/editor/components/QueryHistoryTable.vue
  desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceGutterHandler.ts
  desktop/core/src/desktop/js/apps/editor/components/executableStateHandler.js
  desktop/core/src/desktop/js/apps/editor/components/executionAnalysis/ExecutionAnalysisPanel.vue
  desktop/core/src/desktop/js/apps/editor/components/ko.executableLogs.js
  desktop/core/src/desktop/js/apps/editor/components/result/ResultTable.vue
  desktop/core/src/desktop/js/apps/editor/components/resultChart/ko.resultChart.js
  desktop/core/src/desktop/js/apps/editor/execution/events.ts
  desktop/core/src/desktop/js/apps/editor/execution/executable.ts
  desktop/core/src/desktop/js/apps/editor/execution/executionLogs.ts
  desktop/core/src/desktop/js/apps/editor/execution/executionResult.ts
  desktop/core/src/desktop/js/apps/editor/snippet.js
  desktop/core/src/desktop/js/components/utils/SubscriptionTracker.ts
  desktop/core/src/desktop/js/ko/bindings/ace/aceGutterHandler.js
  desktop/core/src/desktop/js/utils/huePubSub.ts
Labels: autosquash

#1912 [ci] Also check stale PRs
  .github/workflows/autoclose-stale.yml
Labels: autosquash

#1915 [ci] Refactor stale yml into issue and PR sections
  .github/workflows/autoclose-stale.yml
Labels: autosquash

#1916 [ci] Only run autosquash on PR not coming from a Fork
  .github/workflows/autosquash.yml
Labels: autosquash

#1935 [core] Sharing document is always turned off
  desktop/core/src/desktop/js/apps/editor/EditorViewModel.js
Labels: autosquash

#1936 [sqlalchemy] Avoid errors from auto explain query
  desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
Labels: autosquash

#1937 [optimize] Avoid bubbling-up errors when no activated
  desktop/libs/metadata/src/metadata/optimizer/optimizer_client.py
  desktop/libs/metadata/src/metadata/optimizer/optimizer_rest_client.py
  desktop/libs/metadata/src/metadata/optimizer_api.py
Labels: autosquash

#1938 [k8s] Use gunicorn sync mode in helm install for now
  tools/kubernetes/helm/hue/Chart.yaml
  tools/kubernetes/helm/hue/values.yaml
Labels: autosquash

#1940 [docs] User concept section improvements
  docs/docs-site/content/user/concept/_index.md
Labels: docs

#1953 [core] Enable link sharing option not propagated to UI
  desktop/core/src/desktop/templates/global_js_constants.mako
Labels: autosquash

#1963 [sqlalchemy] Avoid column autocomplete errors on unknown tables
  desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
Labels: autosquash
