Repository cloudera/hue, pull requests merged in 2021-04, with the labels that each got.

#1968 [lib] Revert django-axe 4.5.3 DB migration of `axes_accessattempt.trusted`
  desktop/core/ext-py/django-axes-4.5.4/axes/migrations/0006_add_accessattempt_trusted.py
Labels: autosquash

#1970 [demo] Removing pack-lock for now
  tools/examples/components/sql-scratchpad/package-lock.json
Labels: autosquash

#1971 [lib] Revert django-axe 4.5.3 Model removale of trusted column
  desktop/core/ext-py/django-axes-4.5.4/.travis.yml
  desktop/core/ext-py/django-axes-4.5.4/axes/admin.py
  desktop/core/ext-py/django-axes-4.5.4/axes/attempts.py
  desktop/core/ext-py/django-axes-4.5.4/axes/migrations/0006_add_accessattempt_trusted.py
  desktop/core/ext-py/django-axes-4.5.4/axes/models.py
Labels: autosquash

#1975 [ci] Avoid staleness on any issue or PR part of any milestone
  .github/workflows/autoclose-stale.yml
Labels: autosquash

#1974 [blog] Adding Phoenix tech talk on querying HBase via SQL
  docs/gethue/content/en/posts/2021-04-05-interactively-querying-hbase-via-sql-tech-talk.md
Labels: autosquash

#1982 [lib] Make sure cors setting can work with Python 2
  desktop/core/src/desktop/settings.py
Labels: autosquash

#1984 [ci] Ignore LDAP tests warnings to avoid GH false positive checks
  apps/useradmin/src/useradmin/test_ldap.py
  apps/useradmin/src/useradmin/test_ldap_deprecated.py
Labels: autosquash

#2006 [ui] Also patch another jquery.notify plugin
  desktop/core/src/desktop/js/jquery/plugins/jquery.notify.js
  desktop/core/src/desktop/static/desktop/js/jquery.notify.js
Labels: autosquash

#2003 [docker] Adding example of NGINX timeout setting
  tools/docker/nginx/nginx.conf
Labels: autosquash

#2010 [docs] Update gethue/hue install for helm3
  README.md
  docs/docs-site/content/administrator/installation/cloud.md
  docs/docs-site/content/quickstart/_index.md
  docs/docs-site/content/releases/release-notes-4.9.0.md
  docs/gethue/content/en/posts/2019-07-26-hue-in-kubernetes.md
  docs/gethue/content/en/posts/2019-08-12-hue-4-5-and-its-improvements-are-out.md
  docs/gethue/content/en/posts/2019-12-03-release-hue-4-6.md
  docs/gethue/content/en/posts/2020-04-10-release-hue-4-7.md
  docs/gethue/content/en/posts/2020-08-22-quickstart-hue-in-kubernetes.md
  docs/gethue/content/en/posts/2020-09-23-release-hue-4-8.md
  docs/gethue/content/en/posts/2021-02-02-release-hue-4-9.md
  docs/gethue/content/jp/posts/2019-07-28-hue-in-kubernetes.md
  docs/gethue/content/jp/posts/2019-08-14-hue-4-5-and-its-improvements-are-out.md
  docs/gethue/content/jp/posts/2019-12-03-release-hue-4-6.md
  docs/gethue/content/jp/posts/2020-04-10-release-hue-4-7.md
  docs/gethue/content/jp/posts/2020-09-23-release-hue-4-8.md
  docs/gethue/content/jp/posts/2021-02-02-release-hue-4-9.md
  tools/kubernetes/README.md
Labels: autosquash

#1991 [docs] Add separate Slack sections in User Concepts and Admin Configuration docs
  docs/docs-site/content/administrator/configuration/server/_index.md
  docs/docs-site/content/user/concept/_index.md
Labels: docs

#2009 [k8s] Refresh to work easily with helm3 and publick repo
  desktop/core/requirements.txt
  tools/docker/hue/README.md
  tools/kubernetes/helm/hue/Chart.yaml
  tools/kubernetes/helm/hue/README.md
  tools/kubernetes/helm/hue/templates/NOTES.txt
  tools/kubernetes/helm/hue/values.yaml
Labels: autosquash

#1992 [blog] Adding Introducing Slack Integration for Hue blog post
  docs/gethue/content/en/posts/2021-04-09-collaborate-on-your-sql-queries-and-results-directly-within-slack.md
Labels: blog

#2015 [blog] Distribute your container App as a Package
  docs/gethue/content/en/posts/2021-04-19-publish-kubernetes-container-application-via-package-with-helm.md
Labels: autosquash

#2016 [site] Update or remove very old links that are now broken
  apps/filebrowser/src/filebrowser/static/filebrowser/help/index.html
  apps/hbase/example/documents/gethue.com.html
  docs/docs-site/content/_index.md
  docs/docs-site/content/developer/development/_index.md
  docs/docs-site/content/releases/release-notes-1.1.0.md
  docs/docs-site/content/releases/release-notes-1.2.0.md
  docs/docs-site/content/releases/release-notes-2.2.0.md
  docs/docs-site/content/releases/release-notes-2.3.0.md
  docs/gethue/content/en/posts/2012-06-04-hue-2-0.md
  docs/gethue/content/en/posts/2012-10-01-whats-new-in-hue-2-1.md
  docs/gethue/content/en/posts/2012-12-15-how-to-manage-permissions-in-hue.md
  docs/gethue/content/en/posts/2013-01-15-the-dynamic-workflow-builder-in-hue.md
  docs/gethue/content/en/posts/2013-01-20-how-to-import-a-pre-existing-oozie-workflow-into-hue.md
  docs/gethue/content/en/posts/2013-02-15-whats-new-in-hue-2-2.md
  docs/gethue/content/en/posts/2013-03-01-demo-hdfs-file-operations-made-easy-with-hue.md
  docs/gethue/content/en/posts/2013-03-11-tutorial-analyzing-data-with-hue-and-hive.md
  docs/gethue/content/en/posts/2013-04-16-whats-new-in-hue-2-3.md
  docs/gethue/content/en/posts/2013-05-07-tutorial-executing-hive-or-impala-queries-with-python.md
  docs/gethue/content/en/posts/2013-05-13-single-sign-on-in-hue-with-twitter-and-oauth.md
  docs/gethue/content/en/posts/2013-05-28-tutorial-apache-pig-editor-in-hue-2-3.md
  docs/gethue/content/en/posts/2013-06-11-hue-2-4-is-released.md
  docs/gethue/content/en/posts/2013-07-16-hue-2-5-and-its-hbase-app-is-out.md
  docs/gethue/content/en/posts/2013-09-23-hue-3-and-the-new-sqoop-and-zookeeper-apps-are-out.md
  docs/gethue/content/en/posts/2013-10-01-group-synchronization-backends-in-hue.md
  docs/gethue/content/en/posts/2013-10-10-password-management-in-hue.md
  docs/gethue/content/en/posts/2014-03-26-hue-2-5-et-son-hbase-application-est-sorti.md
  docs/release-notes/release-notes-1.1.0.txt
  docs/release-notes/release-notes-1.2.0.txt
  docs/release-notes/release-notes-2.2.0.txt
  docs/release-notes/release-notes-2.3.0.txt
  docs/sdk/sdk.md
Labels: autosquash

#2007 [docs] Refresh of SQL Scratchpad component
  CONTRIBUTING.md
  docs/docs-site/content/developer/components/scratchpad/_index.md
Labels: autosquash

#2018 [blog] Fix Development category tag to be properly displayed
  docs/gethue/content/en/posts/2013-05-07-tutorial-executing-hive-or-impala-queries-with-python.md
  docs/gethue/content/en/posts/2013-05-13-single-sign-on-in-hue-with-twitter-and-oauth.md
  docs/gethue/content/en/posts/2013-09-25-sso-with-hue-new-saml-backend.md
  docs/gethue/content/en/posts/2013-10-01-group-synchronization-backends-in-hue.md
  docs/gethue/content/en/posts/2013-10-10-password-management-in-hue.md
  docs/gethue/content/en/posts/2013-11-08-integrate-external-web-applications-in-any-language.md
  docs/gethue/content/en/posts/2014-01-02-a-better-pygresql-support-for-django.md
  docs/gethue/content/en/posts/2014-02-03-how-to-manage-the-hue-database-with-the-shell.md
  docs/gethue/content/en/posts/2014-02-19-how-to-use-the-new-file-types-icons-with-the-hue-sdk-or.md
  docs/gethue/content/en/posts/2014-02-21-san-francisco-developer-get-started-with-the-hue-sdk.md
  docs/gethue/content/en/posts/2014-03-06-how-hue-integrates-hadoop-with-django.md
  docs/gethue/content/en/posts/2014-03-14-how-to-fix-the-multipleobjectsreturned-error-in-hue.md
  docs/gethue/content/en/posts/2014-04-04-how-to-fix-map.md
  docs/gethue/content/en/posts/2014-06-11-how-to-use-the-new-chart-icons-with-the-hue-sdk-or-in-standalone.md
  docs/gethue/content/en/posts/2014-06-12-i-put-a-proxy-on-hue.md
  docs/gethue/content/en/posts/2014-07-15-how-to-fix-the-bignumbers-results-on-beeswax-and-impala.md
  docs/gethue/content/en/posts/2014-07-17-rbtools-example-how-do-easily-do-code-reviews-with-review-board.md
  docs/gethue/content/en/posts/2014-07-24-tutorial-how-to-run-the-hue-integration-tests.md
  docs/gethue/content/en/posts/2014-09-11-how-to-build-hue-on-ubuntu-14-04-trusty.md
  docs/gethue/content/en/posts/2014-10-02-how-to-configure-hue-in-your-hadoop-cluster.md
  docs/gethue/content/en/posts/2014-11-22-updated-saml-2-0-support.md
  docs/gethue/content/en/posts/2015-01-21-automatic-high-availability-with-hue-and-cloudera-manager.md
  docs/gethue/content/en/posts/2015-02-08-hue-api-execute-some-builtin-commands.md
  docs/gethue/content/en/posts/2015-03-23-start-developing-hue-on-a-mac-in-a-few-minutes.md
  docs/gethue/content/en/posts/2015-03-26-add-a-top-banner-to-hue.md
  docs/gethue/content/en/posts/2015-03-26-using-nginx-to-speed-up-hue-3-8-0.md
  docs/gethue/content/en/posts/2015-04-08-developer-guide-on-upgrading-apps-for-django-1-6.md
  docs/gethue/content/en/posts/2015-07-27-enhance-search-results.md
  docs/gethue/content/en/posts/2015-09-24-how-to-use-the-livy-spark-rest-job-server-for-interactive-spark-2-2.md
  docs/gethue/content/en/posts/2015-10-13-how-to-use-the-livy-spark-rest-job-server-api-for-sharing-spark-rdds-and-contexts.md
  docs/gethue/content/en/posts/2015-10-21-how-to-use-the-livy-spark-rest-job-server-api-for-submitting-batch-jar-python-and-streaming-spark-jobs.md
  docs/gethue/content/en/posts/2015-10-27-performance-tuning.md
  docs/gethue/content/en/posts/2016-05-04-the-hue-team-development-process.md
  docs/gethue/content/en/posts/2016-07-19-change-your-maps-look-and-feel.md
  docs/gethue/content/en/posts/2016-07-22-login-into-hue-using-the-python-request-library.md
  docs/gethue/content/en/posts/2019-07-19-build-your-own-autocompleter.md
  docs/gethue/content/en/posts/2019-09-24-introducing-request-tracing-with-opentracing-and-jaeger-in-kubernetes.md
  docs/gethue/content/en/posts/2020-02-27-using-sql-parser-module.md
  docs/gethue/content/en/posts/2020-04-01-hue-active-users-metric.md
  docs/gethue/content/en/posts/2020-06-22-automated-checking-licenses-absolute-paths-continuous-integration.md
  docs/gethue/content/en/posts/2020-06-23-monitoring-hue-activity-with-grafana-dashboards.md
  docs/gethue/content/en/posts/2020-08-15-automated-checking-python-style-lint-git-commit-messages-continuous-integration.md
  docs/gethue/content/en/posts/2020-09-14-rest-api-querying.md
  docs/gethue/content/en/posts/2021-03-04-vue3-build-cli-options-composition-api-template-web-components-hue.md
  docs/gethue/content/en/posts/2021-03-09-process-and-learnings-when-upgrading-the-webserver-stack-django-upgrade-1.11-to-3.1.md
  docs/gethue/content/jp/posts/2020-02-27-using-sql-parser-module.md
  docs/gethue/content/jp/posts/2020-09-14-rest-api-querying.md
  docs/gethue/content/jp/posts/2021-03-04-vue3-build-cli-options-composition-api-template-web-components-hue.md
  docs/gethue/content/jp/posts/2021-03-09-process-and-learnings-when-upgrading-the-webserver-stack-django-upgrade-1.11-to-3.1.md
Labels: autosquash

#2019 [docs] Add how to refresh the helm package
  docs/docs-site/content/developer/development/_index.md
Labels: autosquash

#2020 [oozie] Fix wrong if comparisons triggering warnings
  apps/oozie/src/oozie/importlib/workflows.py
Labels: autosquash

#2024 [sqlalchemy] Avoid error if the dialect does not support get_view_names
  desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
Labels: autosquash

#2032 [flink] Handle better expired queries
  desktop/libs/dashboard/src/dashboard/models.py
  desktop/libs/kafka/src/kafka/ksql_client.py
  desktop/libs/metadata/src/metadata/optimizer_api.py
  desktop/libs/notebook/src/notebook/connectors/flink_sql.py
Labels: autosquash

#2033 [raz] Skeleton of Python Raz Client tests
  desktop/core/src/desktop/lib/raz/clients.py
  desktop/core/src/desktop/lib/raz/clients_test.py
Labels: autosquash

#2034 [raz] Fix a few typos in the README
  desktop/core/src/desktop/lib/raz/README.md
Labels: autosquash

#2038 [api] Add a auto login flag for testing purpose
  desktop/core/src/desktop/conf.py
  desktop/core/src/desktop/middleware.py
Labels: autosquash

#2040 [s3] Propagate prefix key filter to Bucket list key call
  desktop/libs/aws/src/aws/s3/s3connection.py
Labels: autosquash

#2037 [sqlalchemy] Handle when /autocomplete API used to check if table exists
  desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
Labels: autosquash

#2042 [raz] Unmarshall bucket object fully
  desktop/libs/aws/src/aws/s3/s3connection.py
  desktop/libs/aws/src/aws/s3/s3fs.py
Labels: autosquash

#2043 [blog] How to give end user S3 access without giving away credentials
  docs/gethue/content/en/posts/2021-04-23-s3-file-access-without-any-credentials-and-signed-urls.md
Labels: autosquash

#2044 [raz] Currently need basic Key class as 404 on directories via stats_key()
  desktop/libs/aws/src/aws/s3/s3connection.py
Labels: autosquash
