Repository cloudera/hue, pull requests merged in 2022-05, with the labels that each got.

#2834 CircleCI: Add build jobs that run on Linux ARM64
  .circleci/config.yml
  .github/workflows/commitflow-py3.yml
  Makefile
Labels: feature, tools

#2839 [ui] Check for yarn config when adding application job ids
  desktop/core/src/desktop/js/apps/notebook/snippet.js
Labels: improvement, hive, javascript, frontend

#2853 [ui] Improve yarn config check for skipping job names in log div
  desktop/core/src/desktop/js/apps/notebook/snippet.js
Labels: improvement, ui, javascript

#2852 Change impersonation to use principal_username broke phoenixdb
  desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
  desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py
Labels: phoenix, dialect
